# Generated by Django 5.0.3 on 2024-04-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryitem_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
