# Generated by Django 4.2.10 on 2024-04-16 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryorder_date_time'),
        ('inventory', '0012_product_productitem'),
    ]

    operations = [
    ]
